services:
    web:
        build:
            context: .docker
            dockerfile: ./Dockerfile_web
        volumes:
            - ./:/var/www/html
            - ./.docker/php-fpm.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
        working_dir: /var/www/html
        user: "${UID}:${GID}"
        depends_on:
            - redis_server
        expose:
            - "9000"
        ports:
            - "2345:2345"
            - "8000:8000"
        extra_hosts:
            - host.docker.internal:host-gateway

    nginx:
        build:
            context: .docker
            dockerfile: ./Dockerfile_nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www/html
            - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - web
            - redis_server

    redis_server:
        image: redis:latest
        expose:
            - "6379"
