FROM php:8.3-fpm

ARG UID=1000
ARG GID=1000

# download and set ext installer
ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

# install required php modules
RUN chmod +x /usr/local/bin/install-php-extensions \
    && install-php-extensions gd intl zip bcmath pcntl exif sqlite3 sockets \
    && rm /usr/local/bin/install-php-extensions

# install composer from composer image
COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer

# install node deps
RUN apt-get update && apt-get install -y ca-certificates curl gnupg \
  && curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg \
  && export NODE_MAJOR=20 \
  && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list \
  && apt-get update \
  && apt-get install -y nodejs \
  && npm i -g npm

# set www-data permissions to match default user
RUN usermod -u $UID www-data \
    && groupmod -g $GID www-data \
    && mkdir -p "/home/www-data" \
    && chown -R "${UID}:${GID}" "/home/www-data/" \
    && usermod -d "/home/www-data" www-data
