FROM nginx:latest

# Generate self signed cert
RUN mkdir -p /etc/nginx/certs \
    && cd /etc/nginx/certs \
    && openssl req -x509 -newkey rsa:4096 -keyout site.key -out site.crt -sha256 -days 3650 -nodes -subj "/C=XX/ST=Development/L=Development/O=Development/OU=Development/CN=localhost"
